Orca 105/nf validate dag
Sage-Bionetworks-Workflows/orca-recipes-astro pull request #3
Opened 2022-11-22 23:58 UTC by BWMac

This PR adds the nf-validate dag. It is basic and somewhat hard-coded for this current version. It follows the same basic pattern as the nf-hello dag, and will be further developed in the future to allow more parameters and configuration by users. It has been tested both locally and in the ec2 instance.

2022-11-23 05:25 UTC, thomasyu888 reviewed
LGTM. I think whats important of for me isn't `launch_tower_workflow` having parameters added to it, but that the `launch_workflow` command successfully launches a workflow on Tower and the execution on Tower is successful.

2022-11-23 05:25 UTC, thomasyu888 commented on dags/nf-validate.py
> +            user_secrets=["SYNAPSE_AUTH_TOKEN"], # TODO need to get a workspace secret in the HTAN tower workspace that has more access - don't have permission to create one
@BrunoGrandePhD Can you work with Brad to ensure he has access to create a workspace secret?  

This is out of scope for this ticket, but we need to eventually think about potentially using the "production google account" to log into tower workspace and obtain an access token so that these Airflow DAGs can trigger workflows across all workspaces.  That said, to be on the safer side, once we have a production deployment for Airflow, we would be able to leverage secrets to inject different user's TOWER_ACCESS_TOKENS.

2022-11-23 05:25 UTC, thomasyu888 commented on dags/nf-validate.py
> +            profiles=["docker"],
Should there be a test profile here too?

2022-11-23 05:25 UTC, thomasyu888 commented on dags/nf-validate.py
> +            revision="main",
Does there need to be a `parameters` argument here to produce a successful Tower execution of the workfow?

2022-11-23 18:18 UTC, BWMac commented on dags/nf-validate.py
> +            revision="main",
the workflow has parameters set to defaults for `params.input` and `params.parent_folder`, so the workflow can run without specifying `parameters` in the DAG. If you did specify those parameters in the DAG, they would overwrite the defaults which will likely be what users will do in the future.

2022-11-23 18:27 UTC, thomasyu888 commented on dags/nf-validate.py
> +            revision="main",
Excellent, Thanks!  I noticed that when I ran the workflow last night.

2022-11-23 19:12 UTC, BrunoGrandePhD commented on dags/nf-validate.py
> +            profiles=["docker"],
In a past PR, we discussed the option of a test profile. It hasn't been implemented yet. I'll likely be adding it when I tackle the non-OME TIFF validation work.

2022-11-23 19:20 UTC, BrunoGrandePhD requested changes

2022-11-23 19:20 UTC, BrunoGrandePhD commented on dags/nf-validate.py
> +            user_secrets=["SYNAPSE_AUTH_TOKEN"], # TODO need to get a workspace secret in the HTAN tower workspace that has more access - don't have permission to create one
As a maintainer on the `htan-project` ([source](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/6e4c8a797e8333e9c2f85b9ccad4dde50f56dc10/config/projects-prod/htan-project.yaml#L11)), Brad should be able to create workspace secrets. 

Note that it's under the Secrets tab, not the credentials tab. 

![image](https://user-images.githubusercontent.com/740725/203629109-b28ccae4-35da-4310-958c-71ee8f6f9104.png)

2022-11-23 19:20 UTC, BrunoGrandePhD commented on dags/nf-validate.py
> +            profiles=["docker"],
In a past PR, we discussed the option of a test profile. It hasn't been implemented yet. I'll likely be adding it when I tackle the non-OME TIFF validation work.

2022-11-23 19:20 UTC, BrunoGrandePhD commented on dags/nf-validate.py
> +        return {"tower_utils": tower_utils}
I don't feel comfortable storing a authentication token in the Airflow database, presumably in plain text. 

I advise against testing this DAG with a real project like HTAN until we figure out proper handling of secrets in Airflow (_e.g._ using [Connections](https://airflow.apache.org/docs/apache-airflow/stable/concepts/connections.html)).

2022-11-23 22:20 UTC, thomasyu888 commented on dags/nf-validate.py
> +        return {"tower_utils": tower_utils}
Good point @BrunoGrandePhD - I recommend that we close ORCA-105, create a ticket to update this PR with proper secret management, and leave this PR open.  My personal risk assessment of this is that this is a low-medium risk (more on the low side).  Here are some reasons / questions how I came to this conclusion:

1. Our current deployment of Airflow / Database is password protected and sits behind our VPN and is password protected.
2. Do we have a workspace for sole testing purposes in the scenario that the tower access token is compromised?   I imagine the most severe scenario is if the API is used to delete workflow runs or the workspace itself, but I also can't speak to the probability of someone gaining access to this tower access token.
3. For security, let's rotate our tower access tokens after the Orca prototyping phase.
4. Secrets are out of scope for ORCA-1, but I'll add a ticket in the TIF validation epic to add support for secrets using [this](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/secrets-backend/local-filesystem-secrets-backend.html).  That said, depending on the production deployment of airflow, we may have a different approach for interacting with secrets.

2022-11-24 00:08 UTC, BrunoGrandePhD commented on dags/nf-validate.py
> +        return {"tower_utils": tower_utils}
Since we cannot control who can access the D&T AWS account, I would look into switching to our Tower-dev instance. This way, tokens are for an AWS account that has zero PHI data. One caveat is that we cannot test using PHI data, but I'm hoping we can test using open data in the meantime (or data that has been vetted to be PHI-free).

2022-11-24 00:11 UTC, BrunoGrandePhD commented on dags/nf-validate.py
> +        return {"tower_utils": tower_utils}
Here's a PR for this: https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/pull/148

2022-11-24 00:23 UTC, BrunoGrandePhD commented on dags/nf-validate.py
> +        return {"tower_utils": tower_utils}
By the way, the Tower-dev instance is hosted here: https://tower-dev.sagebionetworks.org/

You should (soon) be able to see an `orca-dev-project` Tower workspace (assuming that this [build](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/actions/runs/3536647813) works).

2022-12-09 17:16 UTC, thomasyu888 approved these changes

2023-02-15 16:28 UTC, closed without merging